#
# Update the versions in this file.
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds
  - argo-events-sa.yaml
  - eventsource-controller
  - sensor-controller
  - eventbus-controller

images:
  - name: argoproj/sensor-controller
    newTag: v1.3.0-rc1
  - name: argoproj/eventbus-controller
    newTag: v1.3.0-rc1
  - name: argoproj/eventsource-controller
    newTag: v1.3.0-rc1

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: eventsource-controller
    spec:
      template:
        spec:
          containers:
            - name: eventsource-controller
              env:
                - name: EVENTSOURCE_IMAGE
                  value: argoproj/eventsource:v1.3.0-rc1
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sensor-controller
    spec:
      template:
        spec:
          containers:
            - name: sensor-controller
              env:
                - name: SENSOR_IMAGE
                  value: argoproj/sensor:v1.3.0-rc1
